const cfg=window.APP_CONFIG;if(!cfg||cfg.SUPABASE_URL.includes('PROJECT'))alert('Isi public/config.js terlebih dahulu.');const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);let current=null,profile=null,reports=[],machines=[],active=null;
const $=x=>document.getElementById(x);const toast=t=>{let e=$('toast');e.textContent=t;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),3000)};
async function init(){const{data:{session}}=await sb.auth.getSession();if(session)await enter(session.user)}
$('loginForm').onsubmit=async e=>{e.preventDefault();let{data,error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return toast(error.message);await enter(data.user)};
async function enter(user){current=user;let{data,error}=await sb.from('profiles').select('*').eq('id',user.id).single();if(error)return toast('Profile belum dibuat oleh Admin');profile=data;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('who').textContent=profile.full_name+' • '+profile.role;document.querySelectorAll('nav button[class]').forEach(b=>{let allowed=b.classList.contains(profile.role)||profile.role==='admin';b.classList.toggle('hidden',!allowed)});await load();show('dashboard')}
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(id).classList.remove('hidden');render()}
async function load(){let a=await sb.from('machines').select('*').eq('active',true).order('section'),b=await sb.from('reports_view').select('*').order('created_at',{ascending:false});if(a.error||b.error)return toast((a.error||b.error).message);machines=a.data;reports=b.data;$('machineSelect').innerHTML=machines.map(m=>`<option value="${m.id}">${m.section} • ${m.name} • ${m.code}</option>`).join('');render()}
function render(){let o=reports.filter(x=>x.status==='OPEN').length,c=reports.filter(x=>x.status==='CLOSED').length;$('total').textContent=reports.length;$('open').textContent=o;$('closed').textContent=c;$('progress').textContent=reports.length-o-c;$('latest').innerHTML=reports.slice(0,10).map(card).join('')||'Belum ada data';$('jobList').innerHTML=reports.filter(x=>['OPEN','IN_PROGRESS','RETURNED'].includes(x.status)).map(x=>`<article class="card job"><span class="badge">${x.status}</span><h3>${x.report_no} • ${x.machine_name}</h3><p>${x.problem}</p><button onclick="startWork('${x.id}')">MULAI / LANJUTKAN</button></article>`).join('')||'<div class="card">Tidak ada pekerjaan.</div>';$('verifyList').innerHTML=reports.filter(x=>x.status==='REQUEST_CHECK').map(x=>`<article class="card job"><span class="badge">REQUEST CHECK</span><h3>${x.report_no} • ${x.machine_name}</h3><p>${x.action||''}</p><button onclick="startVerify('${x.id}')">CEK HASIL</button></article>`).join('')||'<div class="card">Belum ada Request Check.</div>';$('reportRows').innerHTML=reports.map(x=>`<tr><td>${x.report_no}</td><td>${x.machine_name}</td><td>${x.problem}</td><td>${x.status}</td><td>${x.technician_name||'-'}</td></tr>`).join('')}
function card(x){return `<p><span class="badge">${x.status}</span> <b>${x.report_no} • ${x.machine_name}</b><br>${x.problem}</p>`}
async function upload(file,reportId,stage){if(!file)return null;let ext=file.name.split('.').pop(),path=`${reportId}/${stage}-${Date.now()}.${ext}`;let{error}=await sb.storage.from('work-photos').upload(path,file,{contentType:file.type});if(error)throw error;await sb.from('photos').insert({report_id:reportId,stage,path});return path}
$('createForm').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target),no='RPT-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+String(Date.now()).slice(-5);let{data,error}=await sb.from('reports').insert({report_no:no,machine_id:f.get('machine_id'),reporter_id:current.id,shift:f.get('shift'),priority:f.get('priority'),problem:f.get('problem'),impact:f.get('impact'),status:'OPEN'}).select().single();if(error)throw error;await upload(f.get('photo'),data.id,'PROBLEM');e.target.reset();await load();show('dashboard');toast('Laporan dikirim')}catch(x){toast(x.message)}};
window.startWork=async id=>{active=reports.find(x=>x.id===id);if(active.status!=='IN_PROGRESS'){let{error}=await sb.from('reports').update({status:'IN_PROGRESS',technician_id:current.id,start_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message)}$('workTitle').innerHTML=`<b>${active.report_no} • ${active.machine_name}</b><p>${active.problem}</p>`;show('work')};
$('workForm').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target);let{error}=await sb.from('reports').update({cause:f.get('cause'),action:f.get('action'),spare_part:f.get('spare_part'),tech_note:f.get('tech_note'),status:'REQUEST_CHECK',request_check_at:new Date().toISOString()}).eq('id',active.id);if(error)throw error;await upload(f.get('photo'),active.id,'AFTER_REPAIR');e.target.reset();await load();show('jobs');toast('Request Check dikirim')}catch(x){toast(x.message)}};
window.startVerify=id=>{active=reports.find(x=>x.id===id);$('verifyTitle').innerHTML=`<b>${active.report_no} • ${active.machine_name}</b><p>${active.action||''}</p>`;show('verifyFormPage')};
$('verifyForm').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target),decision=e.submitter.value;if(decision==='CLOSED'&&f.get('production_test')!=='NORMAL')throw Error('Hasil harus NORMAL untuk Closed');let{error}=await sb.from('reports').update({production_test:f.get('production_test'),production_note:f.get('production_note'),status:decision,verifier_id:current.id,verified_at:new Date().toISOString(),closed_at:decision==='CLOSED'?new Date().toISOString():null}).eq('id',active.id);if(error)throw error;await upload(f.get('photo'),active.id,'VERIFICATION');e.target.reset();await load();show('dashboard');toast(decision==='CLOSED'?'Report Closed':'Dikembalikan ke Teknisi')}catch(x){toast(x.message)}};
$('machineForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),{error}=await sb.from('machines').insert({code:f.get('code').toUpperCase(),name:f.get('name'),section:f.get('section')});if(error)return toast(error.message);e.target.reset();await load();toast('Mesin disimpan')};
$('downloadExcel').onclick=async()=>{try{let date=$('reportDate').value,next=new Date(date+'T00:00:00');next.setDate(next.getDate()+1);let rows=reports.filter(r=>r.created_at>=date+'T00:00:00'&&r.created_at<next.toISOString().slice(0,10)+'T00:00:00');let wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Detail');ws.columns=['Report','Mesin','Section','Temuan','Dampak','Prioritas','Status','Operator','Teknisi','Penyebab','Tindakan','Spare Part'].map((x,i)=>({header:x,key:String(i),width:i<3?18:28}));rows.forEach(r=>ws.addRow([r.report_no,r.machine_name,r.section,r.problem,r.impact,r.priority,r.status,r.reporter_name,r.technician_name,r.cause,r.action,r.spare_part]));let ph=wb.addWorksheet('Dokumentasi');let row=1;for(let r of rows){ph.getCell(row,1).value=`${r.report_no} • ${r.machine_name}`;ph.getCell(row,1).font={bold:true};let{data:photos}=await sb.from('photos').select('*').eq('report_id',r.id);let col=1;for(let p of photos||[]){let{data}=await sb.storage.from('work-photos').createSignedUrl(p.path,60);let blob=await fetch(data.signedUrl).then(x=>x.blob()),buf=await blob.arrayBuffer(),ext=blob.type.includes('png')?'png':'jpeg',img=wb.addImage({buffer:buf,extension:ext});ph.addImage(img,{tl:{col:col-1,row:row},ext:{width:230,height:170}});ph.getCell(row+9,col).value=p.stage;col+=4}ph.getRow(row).height=125;row+=12}let buf=await wb.xlsx.writeBuffer(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([buf]));a.download=`Daily_Report_${date}.xlsx`;a.click()}catch(x){toast(x.message)}};
$('reportDate').value=new Date().toISOString().slice(0,10);//if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');init();